services:  
  app:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=tcp:electrodb.database.windows.net,1433;Database=ProyectoASll;User ID=adminsql;Password=Genshinimpact18;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    ports:
      - "8001:8080"